/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedGroceryRouteImport } from './routes/_authenticated/grocery'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHouseholdRouteImport } from './routes/_authenticated/household'
import { Route as AuthenticatedKitchenRouteImport } from './routes/_authenticated/kitchen'
import { Route as AuthenticatedLilyRouteImport } from './routes/_authenticated/lily'
import { Route as AuthenticatedMonthRouteImport } from './routes/_authenticated/month'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPantryRouteImport } from './routes/_authenticated/pantry'
import { Route as AuthenticatedPrepRouteImport } from './routes/_authenticated/prep'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTalkRouteImport } from './routes/_authenticated/talk'
import { Route as AuthenticatedTellLilyRouteImport } from './routes/_authenticated/tell-lily'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedWeekRouteImport } from './routes/_authenticated/week'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroceryRoute = AuthenticatedGroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHouseholdRoute = AuthenticatedHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKitchenRoute = AuthenticatedKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLilyRoute = AuthenticatedLilyRouteImport.update({
  id: '/lily',
  path: '/lily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonthRoute = AuthenticatedMonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPantryRoute = AuthenticatedPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrepRoute = AuthenticatedPrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTalkRoute = AuthenticatedTalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTellLilyRoute = AuthenticatedTellLilyRouteImport.update({
  id: '/tell-lily',
  path: '/tell-lily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeekRoute = AuthenticatedWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/grocery': typeof AuthenticatedGroceryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/household': typeof AuthenticatedHouseholdRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/lily': typeof AuthenticatedLilyRoute
  '/month': typeof AuthenticatedMonthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pantry': typeof AuthenticatedPantryRoute
  '/prep': typeof AuthenticatedPrepRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/talk': typeof AuthenticatedTalkRoute
  '/tell-lily': typeof AuthenticatedTellLilyRoute
  '/today': typeof AuthenticatedTodayRoute
  '/week': typeof AuthenticatedWeekRoute
  '/recipes/$slug': typeof RecipesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/grocery': typeof AuthenticatedGroceryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/household': typeof AuthenticatedHouseholdRoute
  '/kitchen': typeof AuthenticatedKitchenRoute
  '/lily': typeof AuthenticatedLilyRoute
  '/month': typeof AuthenticatedMonthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pantry': typeof AuthenticatedPantryRoute
  '/prep': typeof AuthenticatedPrepRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/talk': typeof AuthenticatedTalkRoute
  '/tell-lily': typeof AuthenticatedTellLilyRoute
  '/today': typeof AuthenticatedTodayRoute
  '/week': typeof AuthenticatedWeekRoute
  '/recipes/$slug': typeof RecipesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/grocery': typeof AuthenticatedGroceryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/household': typeof AuthenticatedHouseholdRoute
  '/_authenticated/kitchen': typeof AuthenticatedKitchenRoute
  '/_authenticated/lily': typeof AuthenticatedLilyRoute
  '/_authenticated/month': typeof AuthenticatedMonthRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pantry': typeof AuthenticatedPantryRoute
  '/_authenticated/prep': typeof AuthenticatedPrepRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/talk': typeof AuthenticatedTalkRoute
  '/_authenticated/tell-lily': typeof AuthenticatedTellLilyRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/week': typeof AuthenticatedWeekRoute
  '/recipes/$slug': typeof RecipesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/favorites'
    | '/grocery'
    | '/home'
    | '/household'
    | '/kitchen'
    | '/lily'
    | '/month'
    | '/onboarding'
    | '/pantry'
    | '/prep'
    | '/settings'
    | '/talk'
    | '/tell-lily'
    | '/today'
    | '/week'
    | '/recipes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/favorites'
    | '/grocery'
    | '/home'
    | '/household'
    | '/kitchen'
    | '/lily'
    | '/month'
    | '/onboarding'
    | '/pantry'
    | '/prep'
    | '/settings'
    | '/talk'
    | '/tell-lily'
    | '/today'
    | '/week'
    | '/recipes/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/discover'
    | '/_authenticated/favorites'
    | '/_authenticated/grocery'
    | '/_authenticated/home'
    | '/_authenticated/household'
    | '/_authenticated/kitchen'
    | '/_authenticated/lily'
    | '/_authenticated/month'
    | '/_authenticated/onboarding'
    | '/_authenticated/pantry'
    | '/_authenticated/prep'
    | '/_authenticated/settings'
    | '/_authenticated/talk'
    | '/_authenticated/tell-lily'
    | '/_authenticated/today'
    | '/_authenticated/week'
    | '/recipes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grocery': {
      id: '/_authenticated/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof AuthenticatedGroceryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/household': {
      id: '/_authenticated/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AuthenticatedHouseholdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kitchen': {
      id: '/_authenticated/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof AuthenticatedKitchenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lily': {
      id: '/_authenticated/lily'
      path: '/lily'
      fullPath: '/lily'
      preLoaderRoute: typeof AuthenticatedLilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/month': {
      id: '/_authenticated/month'
      path: '/month'
      fullPath: '/month'
      preLoaderRoute: typeof AuthenticatedMonthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pantry': {
      id: '/_authenticated/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AuthenticatedPantryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prep': {
      id: '/_authenticated/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof AuthenticatedPrepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/talk': {
      id: '/_authenticated/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof AuthenticatedTalkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tell-lily': {
      id: '/_authenticated/tell-lily'
      path: '/tell-lily'
      fullPath: '/tell-lily'
      preLoaderRoute: typeof AuthenticatedTellLilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/week': {
      id: '/_authenticated/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AuthenticatedWeekRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedGroceryRoute: typeof AuthenticatedGroceryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedHouseholdRoute: typeof AuthenticatedHouseholdRoute
  AuthenticatedKitchenRoute: typeof AuthenticatedKitchenRoute
  AuthenticatedLilyRoute: typeof AuthenticatedLilyRoute
  AuthenticatedMonthRoute: typeof AuthenticatedMonthRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPantryRoute: typeof AuthenticatedPantryRoute
  AuthenticatedPrepRoute: typeof AuthenticatedPrepRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTalkRoute: typeof AuthenticatedTalkRoute
  AuthenticatedTellLilyRoute: typeof AuthenticatedTellLilyRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedWeekRoute: typeof AuthenticatedWeekRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedGroceryRoute: AuthenticatedGroceryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedHouseholdRoute: AuthenticatedHouseholdRoute,
  AuthenticatedKitchenRoute: AuthenticatedKitchenRoute,
  AuthenticatedLilyRoute: AuthenticatedLilyRoute,
  AuthenticatedMonthRoute: AuthenticatedMonthRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPantryRoute: AuthenticatedPantryRoute,
  AuthenticatedPrepRoute: AuthenticatedPrepRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTalkRoute: AuthenticatedTalkRoute,
  AuthenticatedTellLilyRoute: AuthenticatedTellLilyRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedWeekRoute: AuthenticatedWeekRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RecipesSlugRoute: RecipesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
