/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedGroceryRouteImport } from './routes/_authenticated/grocery'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedTellLilyRouteImport } from './routes/_authenticated/tell-lily'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedWeekRouteImport } from './routes/_authenticated/week'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroceryRoute = AuthenticatedGroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTellLilyRoute = AuthenticatedTellLilyRouteImport.update({
  id: '/tell-lily',
  path: '/tell-lily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeekRoute = AuthenticatedWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/recipes/$slug',
  path: '/recipes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/grocery': typeof AuthenticatedGroceryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/tell-lily': typeof AuthenticatedTellLilyRoute
  '/today': typeof AuthenticatedTodayRoute
  '/week': typeof AuthenticatedWeekRoute
  '/recipes/$slug': typeof RecipesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/grocery': typeof AuthenticatedGroceryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/tell-lily': typeof AuthenticatedTellLilyRoute
  '/today': typeof AuthenticatedTodayRoute
  '/week': typeof AuthenticatedWeekRoute
  '/recipes/$slug': typeof RecipesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/grocery': typeof AuthenticatedGroceryRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/tell-lily': typeof AuthenticatedTellLilyRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/week': typeof AuthenticatedWeekRoute
  '/recipes/$slug': typeof RecipesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/grocery'
    | '/onboarding'
    | '/tell-lily'
    | '/today'
    | '/week'
    | '/recipes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/grocery'
    | '/onboarding'
    | '/tell-lily'
    | '/today'
    | '/week'
    | '/recipes/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/discover'
    | '/_authenticated/grocery'
    | '/_authenticated/onboarding'
    | '/_authenticated/tell-lily'
    | '/_authenticated/today'
    | '/_authenticated/week'
    | '/recipes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RecipesSlugRoute: typeof RecipesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grocery': {
      id: '/_authenticated/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof AuthenticatedGroceryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tell-lily': {
      id: '/_authenticated/tell-lily'
      path: '/tell-lily'
      fullPath: '/tell-lily'
      preLoaderRoute: typeof AuthenticatedTellLilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/week': {
      id: '/_authenticated/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AuthenticatedWeekRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/recipes/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedGroceryRoute: typeof AuthenticatedGroceryRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedTellLilyRoute: typeof AuthenticatedTellLilyRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedWeekRoute: typeof AuthenticatedWeekRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedGroceryRoute: AuthenticatedGroceryRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedTellLilyRoute: AuthenticatedTellLilyRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedWeekRoute: AuthenticatedWeekRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RecipesSlugRoute: RecipesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
