INSERT INTO public.recipes (slug, title, tagline, cuisine, meal_types, emoji, base_servings, prep_minutes, cook_minutes, difficulty, ingredients, steps, calories, protein, carbs, fat, fiber, tags, prep_friendly, lily_note) VALUES
('bessara','Bessara Fava Soup','Two ingredients, one very cosy bowl.','Moroccan','{breakfast,lunch}','🫘',4,5,30,'easy',
 '[{"name":"Dried split fava beans","amount":"250 g","category":"Pantry"},{"name":"Garlic","amount":"4 cloves","category":"Produce"},{"name":"Cumin","amount":"2 tsp","category":"Spices"},{"name":"Olive oil","amount":"2 tbsp","category":"Pantry"},{"name":"Paprika","amount":"1 tsp","category":"Spices"}]',
 '["Soak the favas overnight, then drain.","Simmer with garlic and plenty of water for 30 minutes until collapsing.","Blend smooth with cumin and salt, loosening with cooking water.","Serve with olive oil, paprika and warm bread."]',
 290,18,40,7,11,'{"vegan","budget","high-fiber"}',true,'Cheapest protein in the souk, and it freezes perfectly.'),
('yogurt-dates-walnuts','Yoghurt, Dates & Walnuts','Three minutes, no cooking, very satisfying.','Moroccan','{snack,breakfast}','🥛',2,3,0,'easy',
 '[{"name":"Plain yoghurt","amount":"300 g","category":"Dairy"},{"name":"Dates","amount":"4","category":"Produce"},{"name":"Walnuts","amount":"20 g","category":"Pantry"},{"name":"Cinnamon","amount":"1/4 tsp","category":"Spices"},{"name":"Honey","amount":"1 tsp","category":"Pantry"}]',
 '["Spoon the yoghurt into two bowls.","Chop dates and walnuts over the top.","Finish with cinnamon and a thread of honey."]',
 240,12,26,10,3,'{"quick","no-cook","high-protein"}',false,'My go-to when the afternoon slump hits.'),
('sardine-khobz','Sardine Khobz Toast','Tinned sardines, tomato, cumin, done.','Moroccan','{snack,lunch}','🥖',2,7,3,'easy',
 '[{"name":"Khobz or baguette","amount":"1/2 loaf","category":"Bakery"},{"name":"Tinned sardines","amount":"1 tin","category":"Pantry"},{"name":"Tomato","amount":"1","category":"Produce"},{"name":"Cumin","amount":"1/2 tsp","category":"Spices"},{"name":"Lemon","amount":"1/2","category":"Produce"}]',
 '["Toast the bread lightly.","Mash sardines with lemon and cumin.","Spread on the bread and top with sliced tomato and salt."]',
 300,22,28,11,3,'{"budget","high-protein","quick"}',false,'Cheap, filling, and full of omega-3.'),
('baked-spiced-chickpeas','Baked Spiced Chickpeas','Crunchy, snackable, made in one tray.','Moroccan','{snack}','🌰',4,5,30,'easy',
 '[{"name":"Chickpeas","amount":"2 tins","category":"Pantry"},{"name":"Olive oil","amount":"1 tbsp","category":"Pantry"},{"name":"Ras el hanout","amount":"2 tsp","category":"Spices"},{"name":"Paprika","amount":"1 tsp","category":"Spices"}]',
 '["Drain, rinse and dry the chickpeas well.","Toss with oil, spices and salt on a tray.","Bake at 200C for 30 minutes, shaking halfway, until crisp."]',
 180,9,24,6,7,'{"vegan","batch-cook","high-fiber"}',true,'Make a big jar on Sunday and snack all week.'),
('mint-tea-almonds','Mint Tea & Toasted Almonds','The pause in the middle of the afternoon.','Moroccan','{snack}','🍵',2,3,5,'easy',
 '[{"name":"Green tea","amount":"1 tbsp","category":"Pantry"},{"name":"Fresh mint","amount":"1 bunch","category":"Produce"},{"name":"Almonds","amount":"40 g","category":"Pantry"},{"name":"Sugar","amount":"1 tsp","category":"Pantry"}]',
 '["Brew the tea with mint and a little sugar.","Toast the almonds dry in a pan until fragrant.","Sit down properly for five minutes."]',
 150,5,8,12,3,'{"quick","low-calorie"}',false,'A handful of almonds beats a biscuit every time.'),
('harcha','Harcha Semolina Pan Bread','Buttery semolina rounds, crisp outside, soft inside.','Moroccan','{breakfast,snack}','🍞',4,10,12,'easy',
 '[{"name":"Fine semolina","amount":"250 g","category":"Pantry"},{"name":"Butter","amount":"60 g","category":"Dairy"},{"name":"Milk","amount":"120 ml","category":"Dairy"},{"name":"Baking powder","amount":"1 tsp","category":"Pantry"},{"name":"Honey or cheese","amount":"to serve","category":"Pantry"}]',
 '["Rub butter into semolina, salt and baking powder until sandy.","Add milk to bind, rest 10 minutes.","Shape rounds and cook in a dry pan 5-6 minutes each side.","Split and fill with honey or cheese."]',
 350,7,44,16,2,'{"comfort","weekend"}',true,'Cook a batch and reheat in a dry pan — never the microwave.'),
('spiced-omelette','Spiced Tomato Omelette','Eggs, cumin, tomato: dinner in ten minutes.','Moroccan','{breakfast,lunch,dinner}','🍳',2,5,10,'easy',
 '[{"name":"Eggs","amount":"4","category":"Dairy"},{"name":"Tomatoes","amount":"2","category":"Produce"},{"name":"Onion","amount":"1/2","category":"Produce"},{"name":"Cumin","amount":"1 tsp","category":"Spices"},{"name":"Parsley","amount":"1 handful","category":"Produce"},{"name":"Olive oil","amount":"1 tbsp","category":"Pantry"}]',
 '["Soften onion and tomato with cumin for 6 minutes.","Beat the eggs with parsley and salt and pour over.","Cook gently, covered, until just set. Cut into wedges."]',
 290,20,10,19,2,'{"quick","high-protein","budget"}',false,'The dish for nights when nothing is planned.'),
('lentil-herb-salad','Herby Lentil Salad','Cold lentils, lots of herbs, sharp lemon.','Moroccan','{lunch,side}','🥗',4,10,25,'easy',
 '[{"name":"Green lentils","amount":"200 g","category":"Pantry"},{"name":"Red onion","amount":"1/2","category":"Produce"},{"name":"Parsley & coriander","amount":"1 bunch","category":"Produce"},{"name":"Lemon","amount":"1","category":"Produce"},{"name":"Olive oil","amount":"2 tbsp","category":"Pantry"},{"name":"Cumin","amount":"1 tsp","category":"Spices"}]',
 '["Simmer lentils 22 minutes until tender but whole, then cool.","Chop onion and herbs finely.","Toss everything with lemon, oil, cumin and salt."]',
 250,14,34,7,10,'{"vegan","make-ahead","high-fiber"}',true,'Doubles as a side dish or a full lunch with an egg on top.');